<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5euWsSS\ASPTest_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5euWsSS/ASPTest_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5euWsSS.legacy');

    return;
}

if (!\class_exists(ASPTest_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5euWsSS\ASPTest_KernelDevDebugContainer::class, ASPTest_KernelDevDebugContainer::class, false);
}

return new \Container5euWsSS\ASPTest_KernelDevDebugContainer([
    'container.build_hash' => '5euWsSS',
    'container.build_id' => 'e900aa9c',
    'container.build_time' => 1649239666,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5euWsSS');
